model_name: 'esrgan_2d_FE'
data_path: '/big_data/qi1/Celeba/train'
plot_per_iter: 1000
image_size: 64
batch_size: 16
num_epochs: 50
input_channel: 3
lr: 0.0001
n_gpus: 4
update_FE: true
is_FE: true
is_ckp: false
name_ckp: 'TMI_res18_FE'
arch_type: 'resnet18'
D_type: 'Discriminator'
G_type: 'Generator'
